name: Build and Deploy .NET App

# Manual trigger
on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest
    environment: prod  # requires approval if you’ve configured protection on this env

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish artifact
        run: dotnet publish -c Release -o ./publish

      - name: Download Web Deploy
        shell: pwsh
        run: |
          Invoke-WebRequest `
            -Uri "https://download.microsoft.com/download/b/d/8/bd882ec4-12e0-481a-9b32-0fae8e3c0b78/webdeploy_amd64_en-US.msi" `
            -OutFile "webdeploy.msi"

      - name: Install Web Deploy
        shell: pwsh
        run: |
          Start-Process -FilePath "msiexec.exe" `
            -ArgumentList "/i webdeploy.msi /quiet /norestart ADDLOCAL=ALL" `
            -Wait

      - name: Deploy to SmarterASP.NET
        shell: pwsh
        run: |
          & "${env:ProgramFiles}\IIS\Microsoft Web Deploy V4\msdeploy.exe" `
            -source:contentPath="$(System.DefaultWorkingDirectory)\publish" `
            -dest:contentPath=${{ secrets.DEPLOY_SITE }},ComputerName=${{ secrets.DEPLOY_URL }},UserName=${{ secrets.DEPLOY_USER }},Password=${{ secrets.DEPLOY_PASSWORD }},AuthType="Basic" `
            -verb:sync `
            -allowUntrusted
