name: Build and Deploy .NET App

on:
  workflow_dispatch:  # manual trigger only

jobs:
  build-and-deploy:
    runs-on: windows-latest
    environment: prod  # requires manual approval

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish
        run: dotnet publish -c Release -o ./publish

      - name: Install Web Deploy
        run: |
          Invoke-WebRequest -Uri "https://download.microsoft.com/download/D/D/9/DD9DB576-4E2C-4726-9B1D-A3F0D62AE8F5/WebDeploy_amd64_en-US.msi" -OutFile "webdeploy.msi"
          Start-Process msiexec.exe -ArgumentList "/i webdeploy.msi /quiet /norestart" -Wait

      - name: Check msdeploy path
        run: Get-ChildItem "C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe"


      - name: Deploy to SmarterASP.NET
        run: |
          msdeploy.exe ^
            -source:contentPath="$(System.DefaultWorkingDirectory)\publish" ^
            -dest:contentPath=${{ secrets.DEPLOY_SITE }},ComputerName=${{ secrets.DEPLOY_URL }},UserName=${{ secrets.DEPLOY_USER }},Password=${{ secrets.DEPLOY_PASSWORD }},AuthType="Basic" ^
            -verb:sync ^
            -allowUntrusted
