name: Build and Deploy .NET App

# Manual trigger
on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest
    environment: prod  # requires approval if you’ve configured protection on this env

    steps:
      - name: Checkout code
        uses: actions/checkout@v4                                      # checks out your repo so the workflow can access it :contentReference[oaicite:0]{index=0}

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4                                  # sets up .NET CLI environment on the runner :contentReference[oaicite:1]{index=1}
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish artifact
        run: dotnet publish --configuration Release --output ./publish

      - name: Deploy via IIS Deploy Action
        uses: appleboy/iis-deploy@v1                                   # deploys your published folder to IIS via Web Deploy :contentReference[oaicite:2]{index=2}
        with:
          package-path: './publish'
          sitename: ${{ secrets.DEPLOY_SITE }}
          username: ${{ secrets.DEPLOY_USER }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          url:      ${{ secrets.DEPLOY_URL }}
