name: Build and Deploy .NET App

# Manual trigger
on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest
    environment: prod  # requires approval if you’ve configured protection on this env

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish artifact
        run: dotnet publish -c Release -o ./publish

      - name: Download Web Deploy
        shell: pwsh
        run: |
          Invoke-WebRequest `
            -Uri "https://download.microsoft.com/download/b/d/8/bd882ec4-12e0-481a-9b32-0fae8e3c0b78/webdeploy_amd64_en-US.msi" `
            -OutFile "webdeploy.msi"

      - name: Install Web Deploy
        shell: pwsh
        run: |
          Start-Process -FilePath "msiexec.exe" `
            -ArgumentList "/i webdeploy.msi /quiet /norestart ADDLOCAL=ALL" `
            -Wait

      - name: Deploy to SmarterASP.NET
        shell: pwsh
        run: |
          # Determine msdeploy.exe path (x64 then x86)
          $msdeployPath = Join-Path $Env:ProgramFiles 'IIS\Microsoft Web Deploy V4\msdeploy.exe'
          if (-not (Test-Path $msdeployPath)) {
            $msdeployPath = Join-Path $Env:'ProgramFiles(x86)' 'IIS\Microsoft Web Deploy V4\msdeploy.exe'
          }
          if (-not (Test-Path $msdeployPath)) {
            Write-Error "Could not find msdeploy.exe. Checked paths: $Env:ProgramFiles and $Env:'ProgramFiles(x86)'"
            exit 1
          }
          # Deploy
          $publishDir = Join-Path $Env:GITHUB_WORKSPACE 'publish'
          & $msdeployPath \
            -source:contentPath="$publishDir" \
            -dest:contentPath=${{ secrets.DEPLOY_SITE }},ComputerName=${{ secrets.DEPLOY_URL }},UserName=${{ secrets.DEPLOY_USER }},Password=${{ secrets.DEPLOY_PASSWORD }},AuthType="Basic" \
            -verb:sync \
            -allowUntrusted

